//==========================  AUTO-GENERATED FILE  ================================
//
// This file is partially auto-generated.
// If functions are removed, your changes to that function will be lost.
// Parameter types and names however are preserved if the function stays unchanged.
// Feel free to change parameters to be more accurate. 
//
//=============================================================================

#pragma once

#include "clienttypes.h"

class CMsgCellList;

class IClientUser
{
public:
    virtual unknown Unknown_0_DONTUSE() = 0; //argc: -1, index 1
    virtual unknown LogOn(CSteamID steamid) = 0; //argc: 2, index 2
    virtual unknown InvalidateCredentials() = 0; //argc: 2, index 3
    virtual unknown LogOff() = 0; //argc: 0, index 4
    virtual bool BLoggedOn() = 0; //argc: 0, index 5
    virtual unknown GetLogonState() = 0; //argc: 0, index 6
    virtual bool BConnected() = 0; //argc: 0, index 7
    virtual bool BInitiateReconnect() = 0; //argc: 0, index 8
    virtual unknown EConnect() = 0; //argc: 0, index 9
    virtual bool BTryingToLogin() = 0; //argc: 0, index 10
    virtual CSteamID GetSteamID() = 0; //argc: 1, index 11
    virtual unknown GetClientInstanceID() = 0; //argc: 0, index 12
    virtual const char *GetUserCountry() = 0; //argc: 0, index 13
    virtual bool IsVACBanned(AppId_t app) = 0; //argc: 1, index 14
    virtual unknown SetEmail() = 0; //argc: 1, index 15
    virtual unknown SetConfigString() = 0; //argc: 3, index 16
    virtual unknown GetConfigString() = 0; //argc: 4, index 17
    virtual unknown SetConfigInt() = 0; //argc: 3, index 18
    virtual unknown GetConfigInt() = 0; //argc: 3, index 19
    virtual unknown SetConfigBinaryBlob() = 0; //argc: 3, index 20
    virtual unknown GetConfigBinaryBlob() = 0; //argc: 3, index 21
    virtual unknown DeleteConfigKey() = 0; //argc: 2, index 22
    virtual unknown GetConfigStoreKeyName() = 0; //argc: 4, index 23
    virtual unknown InitiateGameConnection(void *pAuthBlob, int cbMaxAuthBlob, CSteamID steamIDGameServer, CGameID gameID, uint32 unIPServer, uint16 usPortServer, bool bSecure) = 0; //argc: 8, index 24
    virtual unknown InitiateGameConnectionOld(void *pAuthBlob, int cbMaxAuthBlob, CSteamID steamIDGameServer, CGameID gameID, uint32 unIPServer, uint16 usPortServer, bool bSecure, void *steam2EncryptionKey, int cbSteam2EncryptionKey) = 0; //argc: 10, index 25
    virtual unknown TerminateGameConnection(uint32 unIPServer, uint16 usPortServer) = 0; //argc: 2, index 26
    virtual unknown TerminateGame() = 0; //argc: 2, index 27
    virtual unknown SetSelfAsChatDestination() = 0; //argc: 1, index 28
    virtual unknown IsPrimaryChatDestination() = 0; //argc: 0, index 29
    virtual void RequestLegacyCDKey(AppId_t nAppID) = 0; //argc: 1, index 30
    virtual unknown AckGuestPass() = 0; //argc: 1, index 31
    virtual unknown RedeemGuestPass() = 0; //argc: 1, index 32
    virtual unknown GetGuestPassToGiveCount() = 0; //argc: 0, index 33
    virtual unknown GetGuestPassToRedeemCount() = 0; //argc: 0, index 34
    virtual unknown GetGuestPassToGiveInfo() = 0; //argc: 9, index 35
    virtual unknown GetGuestPassToGiveOut() = 0; //argc: 1, index 36
    virtual unknown GetGuestPassToRedeem() = 0; //argc: 1, index 37
    virtual unknown GetGuestPassToRedeemInfo() = 0; //argc: 7, index 38
    virtual unknown GetGuestPassToRedeemSenderName() = 0; //argc: 3, index 39
    virtual unknown GetNumAppsInGuestPassesToRedeem() = 0; //argc: 0, index 40
    virtual unknown GetAppsInGuestPassesToRedeem() = 0; //argc: 2, index 41
    virtual unknown GetCountUserNotifications() = 0; //argc: 0, index 42
    virtual unknown GetCountUserNotification() = 0; //argc: 1, index 43
    virtual SteamAPICall_t RequestStoreAuthURL(const char *pchRedirectURL) = 0; //argc: 1, index 44
    virtual unknown SetLanguage() = 0; //argc: 1, index 45
    virtual unknown TrackAppUsageEvent(CGameID gameID, int eAppUsageEvent, const char *pchExtraInfo) = 0; //argc: 3, index 46
    virtual unknown RaiseConnectionPriority() = 0; //argc: 2, index 47
    virtual unknown ResetConnectionPriority() = 0; //argc: 1, index 48
    virtual unknown GetDesiredNetQOSLevel() = 0; //argc: 0, index 49
    virtual unknown BHasCachedCredentials() = 0; //argc: 1, index 50
    virtual unknown SetAccountNameForCachedCredentialLogin() = 0; //argc: 2, index 51
    virtual unknown DestroyCachedCredentials() = 0; //argc: 2, index 52
    virtual unknown GetCurrentWebAuthToken() = 0; //argc: 2, index 53
    virtual unknown RequestWebAuthToken() = 0; //argc: 0, index 54
    virtual unknown SetLoginInformation() = 0; //argc: 3, index 55
    virtual unknown SetTwoFactorCode() = 0; //argc: 1, index 56
    virtual unknown SetLoginToken() = 0; //argc: 2, index 57
    virtual unknown GetLoginTokenID() = 0; //argc: 0, index 58
    virtual unknown ClearAllLoginInformation() = 0; //argc: 0, index 59
    virtual unknown BEnableEmbeddedClient() = 0; //argc: 1, index 60
    virtual unknown ResetEmbeddedClient() = 0; //argc: 1, index 61
    virtual unknown BHasEmbeddedClientToken() = 0; //argc: 1, index 62
    virtual unknown RequestEmbeddedClientToken() = 0; //argc: 1, index 63
    virtual unknown AuthorizeNewDevice() = 0; //argc: 3, index 64
    virtual unknown GetLanguage() = 0; //argc: 2, index 65
    virtual unknown TrackSteamUsageEvent() = 0; //argc: 3, index 66
    virtual unknown SetComputerInUse() = 0; //argc: 1, index 67
    virtual unknown BIsGameRunning() = 0; //argc: 1, index 68
    virtual unknown BIsGameWindowReady() = 0; //argc: 1, index 69
    virtual unknown BUpdateAppOwnershipTicket() = 0; //argc: 2, index 70
    virtual unknown GetCustomBinariesState() = 0; //argc: 3, index 71
    virtual unknown RequestCustomBinaries() = 0; //argc: 4, index 72
    virtual unknown SetCellID() = 0; //argc: 1, index 73
    virtual bool GetCellList(CMsgCellList*) = 0; //argc: 1, index 74
    virtual const char *GetUserBaseFolder() = 0; //argc: 0, index 75
    virtual bool GetUserDataFolder(AppId_t appId, char *pchBuffer, int cubBuffer) = 0; //argc: 3, index 76
    virtual unknown GetUserConfigFolder() = 0; //argc: 2, index 77
    virtual bool GetAccountName(char* buf, int bufLen) = 0; //argc: 2, index 78
    virtual int GetAccountName(CSteamID steamid, char* buf, int bufLen) = 0; //argc: 4, index 79
    virtual unknown IsPasswordRemembered() = 0; //argc: 0, index 80
    virtual unknown IsSiteLicenseAssociationPending() = 0; //argc: 0, index 81
    virtual unknown CheckoutSiteLicenseSeat() = 0; //argc: 1, index 82
    virtual unknown GetAvailableSeats() = 0; //argc: 1, index 83
    virtual unknown GetAssociatedSiteName() = 0; //argc: 0, index 84
    virtual bool BIsRunningInCafe() = 0; //argc: 0, index 85
    virtual bool BAllowCachedCredentialsInCafe() = 0; //argc: 0, index 86
    virtual unknown RequiresLegacyCDKey() = 0; //argc: 2, index 87
    virtual unknown GetLegacyCDKey() = 0; //argc: 3, index 88
    virtual unknown SetLegacyCDKey() = 0; //argc: 2, index 89
    virtual unknown WriteLegacyCDKey() = 0; //argc: 1, index 90
    virtual unknown RemoveLegacyCDKey() = 0; //argc: 1, index 91
    virtual unknown RequestLegacyCDKeyFromApp() = 0; //argc: 3, index 92
    virtual unknown BIsAnyGameRunning() = 0; //argc: 0, index 93
    virtual unknown GetSteamGuardDetails() = 0; //argc: 0, index 94
    virtual unknown GetSentryFileData() = 0; //argc: 1, index 95
    virtual unknown GetTwoFactorDetails() = 0; //argc: 0, index 96
    virtual bool BHasTwoFactor() = 0; //argc: 0, index 97
    virtual unknown GetEmail() = 0; //argc: 3, index 98
    virtual unknown Test_FakeConnectionTimeout() = 0; //argc: 0, index 99
    virtual unknown RunInstallScript() = 0; //argc: 2, index 100
    virtual unknown IsInstallScriptRunning() = 0; //argc: 0, index 101
    virtual unknown GetInstallScriptState() = 0; //argc: 4, index 102
    virtual unknown StopInstallScript() = 0; //argc: 1, index 103
    virtual unknown ResetInstallScript() = 0; //argc: 1, index 104
    virtual unknown SpawnProcess() = 0; //argc: 9, index 105
    virtual unknown GetAppOwnershipTicketLength() = 0; //argc: 1, index 106
    virtual unknown GetAppOwnershipTicketData() = 0; //argc: 3, index 107
    virtual unknown GetAppOwnershipTicketExtendedData() = 0; //argc: 7, index 108
    virtual unknown GetMarketingMessageCount() = 0; //argc: 0, index 109
    virtual unknown GetMarketingMessage() = 0; //argc: 5, index 110
    virtual unknown MarkMarketingMessageSeen() = 0; //argc: 2, index 111
    virtual unknown CheckForPendingMarketingMessages() = 0; //argc: 0, index 112
    virtual HAuthTicket GetAuthSessionTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) = 0; //argc: 3, index 113
    virtual HAuthTicket GetAuthSessionTicketV2(void *pTicket, int cbMaxTicket, uint32 *pcbTicket, const SteamNetworkingIdentity *pSteamNetworkingIdentity) = 0; //argc: 4, index 114
    virtual HAuthTicket GetAuthSessionTicketV3(void *pTicket, int cbMaxTicket, uint32 *pcbTicket, const SteamNetworkingIdentity *pSteamNetworkingIdentity) = 0; //argc: 4, index 115
    virtual HAuthTicket GetAuthTicketForWebApi(const char *pchIdentity) = 0; //argc: 1, index 116
    virtual HAuthTicket GetAuthSessionTicketForGameID() = 0; //argc: 5, index 117
    virtual EBeginAuthSessionResult BeginAuthSession(const void *pAuthTicket, int cbAuthTicket, CSteamID steamID) = 0; //argc: 4, index 118
    virtual void EndAuthSession(CSteamID steamID) = 0; //argc: 2, index 119
    virtual void CancelAuthTicket(HAuthTicket) = 0; //argc: 1, index 120
    virtual unknown IsUserSubscribedAppInTicket() = 0; //argc: 3, index 121
    virtual void AdvertiseGame(CGameID gameid, CSteamID steamIDGameServer, uint32 unIPServer, uint16 usPortServer) = 0; //argc: 5, index 122
    virtual SteamAPICall_t RequestEncryptedAppTicket(void *pDataToInclude, int cbDataToInclude) = 0; //argc: 2, index 123
    virtual bool GetEncryptedAppTicket(void *pTicket, int cbMaxTicket, uint32 *pcbTicket) = 0; //argc: 3, index 124
    virtual int GetGameBadgeLevel(int nSeries, bool bFoil) = 0; //argc: 2, index 125
    virtual int GetPlayerSteamLevel() = 0; //argc: 0, index 126
    virtual unknown SetAccountLimited() = 0; //argc: 1, index 127
    virtual unknown BIsAccountLimited() = 0; //argc: 0, index 128
    virtual unknown SetAccountCommunityBanned() = 0; //argc: 1, index 129
    virtual unknown BIsAccountCommunityBanned() = 0; //argc: 0, index 130
    virtual unknown SetLimitedAccountCanInviteFriends() = 0; //argc: 1, index 131
    virtual unknown BLimitedAccountCanInviteFriends() = 0; //argc: 0, index 132
    virtual unknown SendValidationEmail() = 0; //argc: 0, index 133
    virtual unknown BGameConnectTokensAvailable() = 0; //argc: 0, index 134
    virtual unknown NumGamesRunning() = 0; //argc: 0, index 135
    virtual unknown GetRunningGameID() = 0; //argc: 2, index 136
    virtual unknown GetRunningGamePID() = 0; //argc: 1, index 137
    virtual unknown RaiseWindowForGame() = 0; //argc: 1, index 138
    virtual unknown GetAccountSecurityPolicyFlags() = 0; //argc: 0, index 139
    virtual unknown BSupportUser() = 0; //argc: 0, index 140
    virtual unknown BNeedsSSANextSteamLogon() = 0; //argc: 0, index 141
    virtual unknown ClearNeedsSSANextSteamLogon() = 0; //argc: 0, index 142
    virtual unknown BIsAppOverlayEnabled() = 0; //argc: 1, index 143
    virtual unknown BOverlayIgnoreChildProcesses() = 0; //argc: 1, index 144
    virtual unknown SetOverlayState() = 0; //argc: 2, index 145
    virtual unknown NotifyOverlaySettingsChanged() = 0; //argc: 0, index 146
    virtual bool BIsBehindNAT() = 0; //argc: 0, index 147
    virtual unknown GetMicroTxnAppID() = 0; //argc: 2, index 148
    virtual unknown GetMicroTxnOrderID() = 0; //argc: 2, index 149
    virtual unknown BGetMicroTxnPrice() = 0; //argc: 6, index 150
    virtual unknown GetMicroTxnSteamRealm() = 0; //argc: 2, index 151
    virtual unknown GetMicroTxnLineItemCount() = 0; //argc: 2, index 152
    virtual unknown BGetMicroTxnLineItem() = 0; //argc: 11, index 153
    virtual unknown BIsSandboxMicroTxn() = 0; //argc: 3, index 154
    virtual unknown BMicroTxnRequiresCachedPmtMethod() = 0; //argc: 3, index 155
    virtual unknown AuthorizeMicroTxn() = 0; //argc: 3, index 156
    virtual unknown BGetWalletBalance() = 0; //argc: 3, index 157
    virtual unknown RequestMicroTxnInfo() = 0; //argc: 2, index 158
    virtual unknown BMicroTxnRefundable() = 0; //argc: 2, index 159
    virtual unknown BGetAppMinutesPlayed() = 0; //argc: 3, index 160
    virtual unknown GetAppLastPlayedTime() = 0; //argc: 1, index 161
    virtual unknown GetAppUpdateDisabledSecondsRemaining() = 0; //argc: 1, index 162
    virtual unknown BGetGuideURL() = 0; //argc: 3, index 163
    virtual unknown BPromptToChangePassword() = 0; //argc: 0, index 164
    virtual unknown BAccountExtraSecurity() = 0; //argc: 0, index 165
    virtual unknown BAccountShouldShowLockUI() = 0; //argc: 0, index 166
    virtual unknown GetCountAuthedComputers() = 0; //argc: 0, index 167
    virtual unknown GetSteamGuardEnabledTime() = 0; //argc: 0, index 168
    virtual unknown SetPhoneIsVerified() = 0; //argc: 1, index 169
    virtual bool BIsPhoneVerified() = 0; //argc: 0, index 170
    virtual unknown SetPhoneIsIdentifying() = 0; //argc: 1, index 171
    virtual bool BIsPhoneIdentifying() = 0; //argc: 0, index 172
    virtual unknown SetPhoneIsRequiringVerification() = 0; //argc: 1, index 173
    virtual bool BIsPhoneRequiringVerification() = 0; //argc: 0, index 174
    virtual unknown Set2ndFactorAuthCode() = 0; //argc: 2, index 175
    virtual unknown SetUserMachineName() = 0; //argc: 1, index 176
    virtual unknown GetUserMachineName() = 0; //argc: 2, index 177
    virtual unknown GetEmailDomainFromLogonFailure() = 0; //argc: 2, index 178
    virtual unknown GetAgreementSessionUrl() = 0; //argc: 0, index 179
    virtual SteamAPICall_t GetDurationControl() = 0; //argc: 0, index 180
    virtual SteamAPICall_t GetDurationControlForApp(AppId_t appid) = 0; //argc: 1, index 181
    virtual bool BSetDurationControlOnlineState(EDurationControlOnlineState eNewState) = 0; //argc: 1, index 182
    virtual bool BSetDurationControlOnlineStateForApp(AppId_t appid, EDurationControlOnlineState eNewState) = 0; //argc: 2, index 183
    virtual unknown BGetDurationControlExtendedResults() = 0; //argc: 3, index 184
    virtual bool BIsSubscribedApp(AppId_t appid) = 0; //argc: 1, index 185
    virtual unknown GetSubscribedApps() = 0; //argc: 3, index 186
    virtual unknown AckSystemIM() = 0; //argc: 2, index 187
    virtual unknown RequestSpecialSurvey() = 0; //argc: 1, index 188
    virtual unknown SendSpecialSurveyResponse() = 0; //argc: 3, index 189
    virtual unknown RequestNotifications() = 0; //argc: 0, index 190
    virtual bool GetAppOwnershipInfo(AppId_t appid, RTime32 *timeCreated, uint32_t *unk, char *countryCode) = 0; //argc: 4, index 191
    virtual unknown SendGameWebCallback() = 0; //argc: 2, index 192
    virtual unknown BIsStreamingUIToRemoteDevice() = 0; //argc: 0, index 193
    virtual unknown BIsCurrentlyNVStreaming() = 0; //argc: 0, index 194
    virtual unknown OnBigPictureForStreamingStartResult() = 0; //argc: 2, index 195
    virtual unknown OnBigPictureForStreamingDone() = 0; //argc: 0, index 196
    virtual unknown OnBigPictureForStreamingRestarting() = 0; //argc: 0, index 197
    virtual unknown StopStreaming() = 0; //argc: 1, index 198
    virtual unknown GetAllAccountFlags() = 0; //argc: 0, index 199
    virtual unknown LockParentalLock() = 0; //argc: 0, index 200
    virtual unknown UnlockParentalLock() = 0; //argc: 1, index 201
    virtual unknown BIsParentalLockEnabled() = 0; //argc: 0, index 202
    virtual unknown BIsParentalLockLocked() = 0; //argc: 0, index 203
    virtual unknown BIsAppBlocked() = 0; //argc: 1, index 204
    virtual unknown BIsAppInBlockList() = 0; //argc: 1, index 205
    virtual unknown BIsFeatureBlocked() = 0; //argc: 1, index 206
    virtual unknown BIsFeatureInBlockList() = 0; //argc: 1, index 207
    virtual unknown GetParentalUnlockTime() = 0; //argc: 0, index 208
    virtual unknown BGetRecoveryEmail() = 0; //argc: 2, index 209
    virtual unknown BIsLockFromSiteLicense() = 0; //argc: 0, index 210
    virtual unknown EIsParentalPlaytimeBlocked() = 0; //argc: 0, index 211
    virtual unknown BGetSerializedParentalSettings() = 0; //argc: 1, index 212
    virtual unknown BGetParentalWebToken() = 0; //argc: 2, index 213
    virtual unknown GetCommunityPreference() = 0; //argc: 1, index 214
    virtual unknown SetCommunityPreference() = 0; //argc: 2, index 215
    virtual unknown GetTextFilterSetting() = 0; //argc: 0, index 216
    virtual unknown BTextFilterIgnoresFriends() = 0; //argc: 0, index 217
    virtual unknown CanLogonOffline() = 0; //argc: 0, index 218
    virtual unknown LogOnOffline() = 0; //argc: 1, index 219
    virtual unknown ValidateOfflineLogonTicket() = 0; //argc: 1, index 220
    virtual unknown BGetOfflineLogonTicket() = 0; //argc: 2, index 221
    virtual unknown UploadLocalClientLogs() = 0; //argc: 0, index 222
    virtual unknown SetAsyncNotificationEnabled() = 0; //argc: 2, index 223
    virtual unknown BIsOtherSessionPlaying() = 0; //argc: 1, index 224
    virtual unknown BKickOtherPlayingSession() = 0; //argc: 0, index 225
    virtual unknown BIsAccountLockedDown() = 0; //argc: 0, index 226
    virtual unknown RequestAccountLinkInfo() = 0; //argc: 0, index 227
    virtual unknown RequestSurveySchedule() = 0; //argc: 0, index 228
    virtual unknown RequestNewSteamAnnouncementState() = 0; //argc: 0, index 229
    virtual unknown UpdateSteamAnnouncementLastRead() = 0; //argc: 3, index 230
    virtual SteamAPICall_t GetMarketEligibility() = 0; //argc: 0, index 231
    virtual unknown UpdateGameVrDllState() = 0; //argc: 3, index 232
    virtual unknown KillVRTheaterPancakeGame() = 0; //argc: 1, index 233
    virtual unknown SetVRIsHMDAwake() = 0; //argc: 1, index 234
    virtual unknown BIsAnyGameOrServiceAppRunning() = 0; //argc: 0, index 235
    virtual unknown BGetAppPlaytimeMap() = 0; //argc: 1, index 236
    virtual unknown BGetAppsLastPlayedMap() = 0; //argc: 1, index 237
    virtual unknown SendSteamServiceStatusUpdate() = 0; //argc: 2, index 238
    virtual unknown RequestSteamGroupChatMessageNotifications() = 0; //argc: 5, index 239
    virtual unknown RequestSteamGroupChatMessageHistory() = 0; //argc: 5, index 240
    virtual unknown RequestSendSteamGroupChatMessage() = 0; //argc: 6, index 241
    virtual unknown OnNewGroupChatMsgAdded() = 0; //argc: 8, index 242
    virtual unknown OnGroupChatUserStateChange() = 0; //argc: 4, index 243
    virtual unknown OnReceivedGroupChatSubscriptionResponse() = 0; //argc: 5, index 244
    virtual bool GetTimedTrialStatus(AppId_t, bool *pUnk, uint32 *punSecondsAllowed, uint32 *punSecondsPlayed) = 0; //argc: 4, index 245
    virtual bool RequestTimedTrialStatus(AppId_t) = 0; //argc: 1, index 246
    virtual unknown PrepareForSystemSuspend() = 0; //argc: 0, index 247
    virtual unknown ResumeSuspendedGames() = 0; //argc: 1, index 248
    virtual unknown GetClientInstallationID() = 0; //argc: 0, index 249
    virtual unknown GetAppIDForGameID() = 0; //argc: 1, index 250
    virtual unknown BDoNotDisturb() = 0; //argc: 0, index 251
    virtual unknown SetAdditionalClientArgData() = 0; //argc: 1, index 252
    virtual unknown GetFamilyGroupID() = 0; //argc: 0, index 253
    virtual unknown GetFamilyGroupName() = 0; //argc: 0, index 254
    virtual unknown GetFamilyGroupRole() = 0; //argc: 0, index 255
    virtual unknown GetFamilyGroupMembers() = 0; //argc: 2, index 256
    virtual unknown GetSharedAppLockInfo() = 0; //argc: 5, index 257
    virtual unknown GetFamilyDLCForApp() = 0; //argc: 2, index 258
    virtual unknown SetPreferredLender() = 0; //argc: 2, index 259
    virtual unknown GetFamilyCopyCounts() = 0; //argc: 1, index 260
    virtual unknown NotifyPendingGameLaunch_FetchSteamStreamingEncoderConfig() = 0; //argc: 1, index 261
    virtual unknown BShouldWaitForSteamStreamingEncoderConfig() = 0; //argc: 1, index 262
    virtual unknown BGetProcessIDsForGame() = 0; //argc: 3, index 263
    virtual unknown CancelLicenseForApp() = 0; //argc: 1, index 264
};