using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Runtime.InteropServices;
using System.Text;
using OpenSteamworks.Attributes;
using OpenSteamworks.Callbacks.Structs;

namespace OpenSteamworks.Callbacks;

/// <summary>
/// The contents of this class get partially autogenerated. Do not rename!
/// </summary>
internal static partial class CallbackMetadata {
	private const string ARRAY_JOIN_SEPARATOR = ", ";
	private const string BYTE_ARRAY_JOIN_SEPARATOR = ", ";

	private static unsafe T GetStructForCallback<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.PublicConstructors | DynamicallyAccessedMemberTypes.NonPublicConstructors)] T>(byte[] data) where T: struct {
		CallbackSizeException.ThrowOrWarn(data.Length, Marshal.SizeOf<T>(), typeof(T).Name);

		fixed (byte* ptr = data) {
			return Marshal.PtrToStructure<T>((nint)ptr);
		}
	}

	private static string EnumerableToString<T>(IEnumerable<T>? obj) {
		if (obj is null || obj == null) {
			return "(null)";
		}

		if (obj is IEnumerable<byte> byteArr)
		{
			return $"[{string.Join(BYTE_ARRAY_JOIN_SEPARATOR, byteArr.Select(b => $"0x{b.ToString("X2")}"))}]";
		}

		return $"[{string.Join(ARRAY_JOIN_SEPARATOR, obj)}]";
	}

	private static string FieldToString(object? obj) {
		if (obj is null) {
			return "(null)";
		}

		try
		{
			// Since this is defined by the object, it can throw exceptions.
			if (obj == null) {
				return "(null)";
			}

			// This is also defined by the object, and can throw exceptions.
			return Convert.ToString(obj) ?? "(null)";
		}
		catch (Exception)
		{
			return "(threw an exception)";
		}
	}
}
