name: .NET Build

# Trigger the workflow on push or pull request
on:
  push:
    branches: ["master"]
    paths:
      - ".github/workflows/dotnet.yaml"
      - "Directory.Build.props"
      - "package-osw.sh"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      name: Download repo
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Build and pack release
      run: ./package-osw.sh

    - name: Set version envs
      run: |
        echo "OSWVersion=$(dotnet msbuild -getproperty:CommonVersion Directory.Build.props)" >> $GITHUB_ENV

    - name: Upload to NuGet.org
      run: |
        dotnet nuget push ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.${{ env.OSWVersion }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Data.${{ env.OSWVersion }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Messaging.${{ env.OSWVersion }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Messaging.SharedConnection.${{ env.OSWVersion }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
        dotnet nuget push ${{ github.workspace }}/artifacts/package/release/OpenSteamworks.Protobuf.${{ env.OSWVersion }}.nupkg --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json